[MF-5] Added features component
Codubee/MathSkillsMW3-4-Front pull request #4
Opened 2021-07-21 20:09 UTC by trexrush

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
New Component / Feature

* **What is the current behavior? What does the code do before you made the new changes?** 
The current code does not have the component implemented, with the content in this pull request the Features Component is now present

* **What is the new behavior?**
A new component that exists to introduce the features of our application to the user

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
Nothing should be broken, but there is a small chance that there might be a few conflicts, since App.js is modified

* **Other information**:

2021-07-26 20:28 UTC, tqyn117 approved these changes

2021-07-26 20:29 UTC, tqyn117 approved these changes, later dismissed
I suggest capitalizing the first letter to improve the look of the feature listing

2021-07-26 20:30 UTC, Codubee commented on src/App.js
> +      <>
Can you change this from <> to a <div> instead please.

2021-07-26 20:30 UTC, Codubee commented on src/components/Features.js
> +export default Features;
I see that this is a class component. Would it be better to do this as a functional component since it is only displaying some text?

2021-07-26 20:31 UTC, Codubee requested changes
Left some comments for discussion

2021-07-28 20:01 UTC, Codubee approved these changes, later dismissed
LGTM!

2021-07-28 20:04 UTC, merged